/*globals define, _, WebGMEGlobal*/
/**
 * Generated by VisualizerGenerator 1.7.0 from webgme on Mon Jul 22 2019 15:40:44 GMT-0700 (PDT).
 */

define([
    'panels/EasyDAG/EasyDAGPanel',
    'widgets/SemanticGraph/SemanticGraphWidget',
    './SemanticGraphControl'
], function (
    EasyDAGPanel,
    SemanticGraphWidget,
    SemanticGraphControl
) {
    'use strict';

    function SemanticGraphPanel(layoutManager, params) {
        EasyDAGPanel.apply(this, arguments);
    }

    SemanticGraphPanel.prototype = Object.create(EasyDAGPanel.prototype);

    SemanticGraphPanel.prototype._initialize = function () {
        var self = this;

        //set Widget title
        this.setTitle('');

        this.widget = new SemanticGraphWidget(this.logger, this.$el);

        this.widget.setTitle = function (title) {
            self.setTitle(title);
        };

        this.control = new SemanticGraphControl({
            logger: this.logger,
            client: this._client,
            widget: this.widget
        });

        this.onActivate();
    };

    return SemanticGraphPanel;
});
