/*globals define, _*/

/**
 * Generated by DecoratorGenerator
 */

define([
    'js/Decorators/DecoratorBase',
    './EasyDAG/SemanticNodeDecorator.EasyDAGWidget'
], function (
    DecoratorBase,
    SemanticNodeDecoratorEasyDAGWidget
) {

    'use strict';

    var DECORATOR_ID = 'SemanticNodeDecorator';

    function SemanticNodeDecorator(params) {
        var opts = _.extend({loggerName: this.DECORATORID}, params);

        DecoratorBase.apply(this, [opts]);

        this.logger.debug('SemanticNodeDecorator ctor');
    }

    _.extend(SemanticNodeDecorator.prototype, DecoratorBase.prototype);
    SemanticNodeDecorator.prototype.DECORATORID = DECORATOR_ID;

    /*********************** OVERRIDE DecoratorBase MEMBERS **************************/

    SemanticNodeDecorator.prototype.initializeSupportedWidgetMap = function () {
        this.supportedWidgetMap = {
            EasyDAG: SemanticNodeDecoratorEasyDAGWidget
        };
    };

    return SemanticNodeDecorator;
});
